[tool.poetry]
name = "yiri-onebot"
version = "0.0.1"
description = "YiriOneBot是一个OneBot 12协议上的Python SDK，延续YiriMirai项目轻量级、低耦合的编码风格。"
authors = ["XYCode Kerman <xycode-xyc@outlook.com>"]
license = "LGPL-3.0"
readme = "README.md"
homepage = "https://github.com/YiriMiraiProject/YiriOneBot"
repository = "https://github.com/YiriMiraiProject/YiriOneBot"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Communications",
  "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
  "Framework :: AsyncIO",

  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]

[[tool.poetry.packages]]
include = "mirai_onebot"

[tool.poetry.dependencies]
python = ">=3.8"
websockets = "^12.0"
rich = "^13.7.0"
objprint = "^0.2.3"
pydantic = "^2.7.4"


[[tool.poetry.source]]
name = "mirrors"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "default"


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.1"
pytest-cov = "^4.1.0"
ipykernel = "^6.29.2"
pytest-asyncio = "^0.23.5"
autoflake = "^2.3.1"
autopep8 = "^2.2.0"
isort = "^5.13.2"
pylint = "^3.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
