---
blank_issues_enabled: false
contact_links:
  - name: Yiri OneBot Community Support
    url: https://github.com/YiriMiraiProject/YiriOneBot/discussions
    about: Please ask and answer questions here.
