from typing import Literal

from pydantic import BaseModel, Field

from .base import EventBase

# Attention!
# All the code below the comment are generated by AI according OneBot 11 Standrad.
# The developer does not approve these code are all right.
# Please check them before you use them.


class File(BaseModel):
    id: str = Field(description="文件 ID")
    name: str = Field(description="文件名")
    size: int = Field(description="文件大小（字节数)")
    busid: int = Field(description="busid（目前不清楚有什么作用）")


class NoticeEvent(EventBase):
    post_type: Literal["notice"] = "notice"  # type: ignore
    notice_type: Literal[
        "group_upload",
        "group_admin",
        "group_decrease",
        "group_increase",
        "group_ban",
        "friend_add",
        "group_recall",
        "friend_recall",
        "poke",
        "lucky_king",
        "notify",
    ]


class GroupUploadNotice(NoticeEvent):
    notice_type: Literal["group_upload"] = "group_upload"  # type: ignore
    group_id: int = Field(description="群号")
    user_id: int = Field(description="发送者 QQ 号")
    file: File = Field(description="文件信息")


class GroupAdminNotice(NoticeEvent):
    notice_type: Literal["group_admin"] = "group_admin"  # type: ignore
    group_id: int = Field(description="群号")
    user_id: int = Field(description="管理员 QQ 号")
    sub_type: Literal["set", "unset"] = Field(
        description="事件子类型，分别表示设置和取消管理员"
    )


class GroupDecreaseNotice(NoticeEvent):
    notice_type: Literal["group_decrease"] = "group_decrease"  # type: ignore
    group_id: int = Field(description="群号")
    operator_id: int = Field(
        description="操作者 QQ 号（如果是主动退群，则和 user_id 相同）"
    )
    user_id: int = Field(description="离开者 QQ 号")
    sub_type: Literal["leave", "kick", "kick_me"] = Field(
        description="事件子类型，分别表示主动退群、成员被踢、登录号被踢"
    )


class GroupIncreaseNotice(NoticeEvent):
    notice_type: Literal["group_increase"] = "group_increase"  # type: ignore
    group_id: int = Field(description="群号")
    operator_id: int = Field(description="操作者 QQ 号")
    user_id: int = Field(description="加入者 QQ 号")
    sub_type: Literal["approve", "invite"] = Field(
        description="事件子类型，分别表示管理员已同意入群、管理员邀请入群"
    )


class GroupBanNotice(NoticeEvent):
    notice_type: Literal["group_ban"] = "group_ban"  # type: ignore
    group_id: int = Field(description="群号")
    operator_id: int = Field(description="操作者 QQ 号")
    user_id: int = Field(description="被禁言 QQ 号")
    sub_type: Literal["ban", "lift_ban"] = Field(
        description="事件子类型，分别表示禁言、解除禁言"
    )
    duration: int = Field(description="禁言时长，单位秒")


class FriendAddNotice(NoticeEvent):
    notice_type: Literal["friend_add"] = "friend_add"  # type: ignore
    user_id: int = Field(description="新添加好友 QQ 号")


class GroupRecallNotice(NoticeEvent):
    notice_type: Literal["group_recall"] = "group_recall"  # type: ignore
    group_id: int = Field(description="群号")
    user_id: int = Field(description="消息发送者 QQ 号")
    operator_id: int = Field(description="操作者 QQ 号")
    message_id: int = Field(description="被撤回的消息 ID")


class FriendRecallNotice(NoticeEvent):
    notice_type: Literal["friend_recall"] = "friend_recall"  # type: ignore
    user_id: int = Field(description="好友 QQ 号")
    message_id: int = Field(description="被撤回的消息 ID")


class PokeNotice(NoticeEvent):
    notice_type: Literal["notify"] = "notify"  # type: ignore
    sub_type: Literal["poke"] = "poke"
    group_id: int = Field(description="群号")
    user_id: int = Field(description="发送者 QQ 号")
    target_id: int = Field(description="被戳者 QQ 号")


class LuckyKingNotice(NoticeEvent):
    notice_type: Literal["notify"] = "notify"  # type: ignore
    sub_type: Literal["lucky_king"] = "lucky_king"
    group_id: int = Field(description="群号")
    user_id: int = Field(description="红包发送者 QQ 号")
    target_id: int = Field(description="运气王 QQ 号")


class HonorChangeNotice(NoticeEvent):
    notice_type: Literal["notify"] = "notify"  # type: ignore
    sub_type: Literal["honor"] = "honor"
    group_id: int = Field(description="群号")
    honor_type: Literal["talkative", "performer", "emotion"] = Field(
        description="荣誉类型，分别表示龙王、群聊之火、快乐源泉"
    )
    user_id: int = Field(description="成员 QQ 号")


# Attention!
# All the code above the comment are generated by AI according OneBot 11 Standrad.
# The developer does not approve these code are all right.
# Please check them before you use them.

__all__ = [
    "File",
    "NoticeEvent",
    "GroupUploadNotice",
    "GroupAdminNotice",
    "GroupDecreaseNotice",
    "GroupIncreaseNotice",
    "GroupBanNotice",
    "FriendAddNotice",
    "GroupRecallNotice",
    "FriendRecallNotice",
    "PokeNotice",
    "LuckyKingNotice",
    "HonorChangeNotice",
]
