from typing import Literal

from pydantic import Field

from .base import EventBase

# Attention!
# All the code below the comment are generated by AI according OneBot 11 Standrad.
# The developer does not approve these code are all right.
# Please check them before you use them.


class RequestEvent(EventBase):
    post_type: Literal["request"] = "request"  # type: ignore
    request_type: Literal["friend", "group"]


class FriendRequest(RequestEvent):
    request_type: Literal["friend"] = "friend"  # type: ignore
    user_id: int = Field(description="发送请求的 QQ 号")
    comment: str = Field(description="验证信息")
    flag: str = Field(description="请求 flag，在调用处理请求的 API 时需要传入")


class GroupRequest(RequestEvent):
    request_type: Literal["group"] = "group"  # type: ignore
    sub_type: Literal["add", "invite"] = Field(
        description="请求子类型，分别表示加群请求、邀请登录号入群"
    )
    group_id: int = Field(description="群号")
    user_id: int = Field(description="发送请求的 QQ 号")
    comment: str = Field(description="验证信息")
    flag: str = Field(description="请求 flag，在调用处理请求的 API 时需要传入")


# Attention!
# All the code above the comment are generated by AI according OneBot 11 Standrad.
# The developer does not approve these code are all right.
# Please check them before you use them.

__all__ = ["RequestEvent", "FriendRequest", "GroupRequest"]
